version: '3.4'

services: 
  app:
    build:
      context: ./
      target: build-env
    volumes:
      - ./cleverit/:/app
    ports:
      - "5000:5000"
      - "5001:5001"
    command: dotnet watch run
